### ISSUE TITLE
Expand conversion types to include string constructor and static factory

### ISSUE THREAD

**Issue by dblevins** [eclipse/microprofile-jwt-auth#114] opened 2018-10-11 18:37 UTC
Our ability to convert Claims from strings to specific data types should be expanded to reach the same level of functionality found in JAX-RS or Config API.  Specifically, java types that have a public constructor that accept a string should be supported, as should java types that have a static factory method that accepts string as an argument and returns an instance of that type.

**Comment by radcortez** [comment] 2020-01-31 17:50
I think this will great to support. On the other hand we are seeing a lot of repetition around conversions. MP Config is pitching the idea of creating a Conversion spec to be used by all the other specs.

Most likely it would be good to push for such a spec, or even provide a way to access MP Config converters until something like this is available.

**Comment by radcortez** [comment] 2020-01-31 18:09
https://github.com/eclipse/microprofile-config/issues/514

**Comment by sberyozkin** [comment] 2020-02-24 14:07
Is it a duplicate of #100 ?

**Comment by sberyozkin** [comment] 2020-02-26 13:55
Hi All and David in particular, @dblevins. David, don;t hate me please for closing another of your issues :-). I will copy this requirement to #100 and credit it to you; IMHO it should also be tied with a type safe retrieval of the claims. see you at #100 later on, cheers

**Closed** 2020-02-26 13:55 UTC
