### ISSUE TITLE
What's the purpose of keeping LoginConfig in a separate package?

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-jwt-auth#237] opened 2021-01-06 14:45 UTC
Unlike all the other elements the `LoginConfig` annotation sits lonely in an `org.eclipse.microprofile.auth` package. 
This is at least weird especially when JPMS (Jigsaw) style modularity comes into play and sooner or later this will affect Jakarta EE given the service loading mechnism via the old "services" folder does not work anymore if you use a newer JDK and modules and it may eventually be replaced completely.

It should work to have more than one top level package even in a modular MP JWT but why was only this annotation separated, was the idea to eventually migrate or graduate it into Jakarta EE annotations?

**Comment by sberyozkin** [comment] 2021-01-06 20:55
Hey @keilw I'm going to close this one as a duplicate of #182 - where we are actually considering to drop this annotation altogether - I'd prefer not to keep one issue discussing removing it and another one proposing a breaking move to a different package - even if we do keep it in 2.0 then it would be the last thing I'd consider prioritizing upon - please do not hesitate to put your argument for keeping it at #182

**Closed by sberyozkin** 2021-01-06 20:55 UTC

**Comment by sberyozkin** [comment] 2021-01-06 21:11
@keilw I commit to re-opening it if the resolution of #182 would be to keep `LoginConfig` around, thank you
