### ISSUE TITLE
Enum injection

### ISSUE THREAD

**Issue by ivanjunckes** [eclipse/microprofile-jwt-auth#101] opened 2018-08-02 14:28 UTC
Hi guys, 

These are the supported values:
java.lang.String
• java.lang.Long
• java.lang.Boolean
• java.util.Set<java.lang.String>
• javax.json.JsonValue.TRUE/FALSE
• javax.json.JsonString
• javax.json.JsonNumber
• javax.json.JsonArray
• javax.json.JsonObject

Shouldn't we also support Enum classes? Strings could be transformed to a Enum using valueOf if the injection point is an Enum class.

What do you guys think?

**Comment by dblevins** [comment] 2018-08-02 20:01
We should have identical conversion capabilities as the Config API.  Last I checked they were something like the following:

 - `public TheType(String)` produce an instance using public string constructor on the type itself.
 - `public static TheType parse(String)` produce an instance using a static factory on the type itself.

There's an order of precedence and if I recall correctly at least one supported more static factory pattern.

**Comment by starksm64** [comment] 2018-08-09 15:06
I think this makes sense.

**Comment by radcortez** [comment] 2020-01-31 18:24
Related with https://github.com/eclipse/microprofile-jwt-auth/issues/114

**Comment by sberyozkin** [comment] 2020-02-24 14:07
Is it a duplicate of #100 ?

**Comment by sberyozkin** [comment] 2020-02-26 13:59
Hi @ivanjunckes all, copying your requirement to #100, to keep it all centralized in one place;
CC @dblevins, @radcortez 
thanks

**Closed by sberyozkin** 2020-02-26 13:59 UTC
Labels: enhancement
