### ISSUE TITLE
Is it possible to @Inject Optional<JsonWebToken> ?

### ISSUE THREAD

**Issue by hrstoyanov** [eclipse/microprofile-jwt-auth#120] opened 2018-12-23 01:18 UTC
It would be really nice, if possible!

**Comment by radcortez** [comment] 2020-03-26 10:37
I'm not sure if we should support this.

`JsonWebToken` by nature is a `RequestScoped` bean, because of course, the JWT is tied to the request. This allows you to inject the `JsonWebToken` in `ApplicationScoped` beans and getting the right token.

Also, `RequestScoped` beans must be proxyable and the issue is that `Optional` is a final class, so it cannot be proxied, meaning that you are not able to inject an `Optional<JsonWebToken>` that is `RequestScoped`

To be able to inject `Optional<JsonWebToken>` this would need be `Dependent` scope. In `Dependent` scope, you get the same lifecycle of bean getting injected. In practice, this means that if you are injecting `Optional<JsonWebToken>` in a `RequestScoped` bean you are fine, but if you do it in a `ApplicationScoped` bean, then you will get the first JWT used to invoke the bean and it will never change again.

**Comment by sberyozkin** [comment] 2020-03-26 15:53
Hi Roberto - thanks a million for starting to look into it.

> but if you do it in a ApplicationScoped bean, then you will get the first JWT used to invoke the bean and it will never change again

That pretty much says it that we can't support it unless some check can be made somewhere to enforce it can never be used with `ApplicationScoped` beans. I've had to deal with a number of issues where the users had the stale tokens leaked into the newer `ApplicationScoped` bean invocations before it was properly fixed, so we definitely do not want to allow even for the accidental leak.

We can say in the spec - be careful with injecting the optional tokens into  `ApplicationScoped` beans ut then what would be the point, most users use `ApplicationScoped` beans. I'm actually keen now to close this issue.

Though, why `Optional` works in other cases, with `ClaimValue`, etc ?

**Comment by radcortez** [comment] 2020-03-26 16:07
Yes, I agree that it might do more harm than good to support this as is, even if we issue a warning in the documentation. Plus, it would be a bad user experience when in one case it works properly and the other case it doesn't.

In `ClaimValue` it does work, because `ClaimValue` is not `final` and can be proxied. The limitation here is that the object being injected has to be proxyable. Internally, the object is free to have any representation, which is fine.

**Comment by radcortez** [comment] 2020-03-26 17:11
An alternative is to inject the JWT with a Provider:

```java
@Inject
private Provider<JsonWebToken> providerJsonWebToken;
```

This should work right now, and the object is only injected when you call `providerJsonWebToken.get()`. It is not exactly the same thing as Optional, because you are safe to call Optional and in here you need to know if you are able to call `.get()` or not, which may require you to go to the `httpRequest` and manually verify there is a JWT in there.

Returning again to the `RequestScope` and `JsonWebToken`, the CDI producer cannot return null, because null is not proxyable either. In SmallRye Config, this is resolved by returning a `NullJsonWebToken` with all the methods returning null as well. How to handle this case is out of the spec, but maybe we could add it. Something like:

`If there is no JWT, an EmptyToken is injected with all values to null`.

Authentication and Authorization would still fail, since nothing there is no information to act upon (actually in SmallRye no changes are required, since this is what we are already doing anyway).

And the `JsonWebToken` can expose a `getOptional`, so you would always be safe. Something like this:

```java
@Inject
JsonWebToken jwt;

Optional<JsonWebToken> = jwt.getOptional();
```

**Comment by sberyozkin** [comment] 2020-03-26 18:38
@radcortez Thanks, something along the lines of
```
If there is no JWT, an EmptyToken is injected with all values to null.
```
would be the best what we can do IMHO instead of making various compromises around `Optional`. `Optional<JsonWebToken>` looks neat but if a thread locality can not be guaranteed for `ApplicationScoped` beans then it does not work, or modifying `JsonWebToken`.

What about 
```
Provider<Optional<JsonWebToken>> providerJsonWebToken
```
?
Thanks

**Comment by sberyozkin** [comment] 2020-03-26 18:41
Even `Provider<JsonWebToken>` - which just doc that one should be prepared to check the exception if it is not resolvable.

**Comment by radcortez** [comment] 2020-03-26 18:45
`Provider<Optional<JsonWebToken>> providerJsonWebToken` doesn't work either because is still subject to the rules of creational bean. Basically is just allows you control when the injection is performed, but the rules are the same.

**Comment by sberyozkin** [comment] 2020-03-27 12:01
@radcortez thanks, I've been warming up to your proposal to just require a `NullJwtWebToken` be returned. 
Then all the user has to do is (which is something we will document):
```
@Inject 
JsonWebToken jwt;
if (jwt.getRawToken() == null) {
   // No Token has been provided in the HTTP request !
}
```
No new methods, thread-safety or RBAC compromises. But if all the user wants to do is to inject the value and introspect it manually - it will do just fine :-).

**Comment by radcortez** [comment] 2020-03-27 12:10
Yes,

I guess we could provide a `getAsOptional()` as a shortcut:

```java
@Inject 
JsonWebToken jwt;
if (jwt.getAsOptional.isPresent()l) {
   // No Token has been provided in the HTTP request !
}
```

Will save:
```java
Optional.ofNullable(jwt.getRawToken())
```

But not really a strong opinion about it. 

The important portion is the spec to specify that an Empty JWT object is injected if no JWT is found in the request. Then the user can do whatever he wants with it.

**Comment by sberyozkin** [comment] 2020-03-27 23:09
@radcortez We already have `JsonWebToken.getRawToken()` method which returns String which is supposed to represent whatever was in `Authorization Bearer ...`, IMHO there is no need for more methods if we are happy with the empty JWT object idea.
We can tweak the text (your `an Empty JWT object is injected if no JWT is found in the request` is just fine :-) ) and add a simple test that all of `JsonWebToken` methods return null and be done with this issue :-)

**Comment by radcortez** [comment] 2020-03-28 13:32
I'm fine with this. I'll push a proposal for spec and implementation.

**Comment by rdebusscher** [comment] 2020-03-28 19:43
When there is no JWT token in the header, a status 401 should be returned and not the execution of the JAX-RS method.

Or am I missing something in the above discussion?

**Comment by radcortez** [comment] 2020-03-29 18:36
The use case is for endpoint that don't require any authentication / authorisation but may have a token sent on the request.

Here is the original issue reported in Liberty:
https://github.com/OpenLiberty/open-liberty/issues/6087

**Comment by Emily-Jiang** [comment] 2020-03-29 23:29
I am a bit confused with this. I think it makes sense to inject `null` when the token cannot be obtained. The producer is allowed to produce a `null`. As for injecting to an `ApplicationScoped` bean, all of the injection points are static and only inject once. I don't think this token has any special dealing with that though.

**Comment by hrstoyanov** [comment] 2020-03-30 02:35
I filed this issue as a possible solution to specific problem in OpenLiberty, which may have been mitigated since then.
See original here:
https://github.com/OpenLiberty/open-liberty/issues/6087

**Comment by radcortez** [comment] 2020-03-30 09:40
> I think it makes sense to inject `null` when the token cannot be obtained. The producer is allowed to produce a `null`.

Per the spec, null cannot be injected if the scope of the producer is something else than `Dependent`. In this case, the spec marks `JsonWebToken` as RequestScoped. Here is the text from the CDI spec as well:

_If a producer method sometimes returns a null value, then the producer method must have scope @Dependent. If a producer method returns a null value at runtime, and the producer method declares any other scope, an IllegalProductException is thrown by the container. This restriction allows the container to use a client proxy, as defined in Client proxies._

> As for injecting to an `ApplicationScoped` bean, all of the injection points are static and only inject once. I don't think this token has any special dealing with that though.

Yes, injection works fine. That is not the issue. The point is that you only get injected once and the value never changes. That is why the `JsonWebToken` is marked as `RequestScope` so you don't have issues with it.

**Comment by radcortez** [comment] 2020-03-30 09:42
> I filed this issue as a possible solution to specific problem in OpenLiberty, which may have been mitigated since then.
> See original here:
> [OpenLiberty/open-liberty#6087](https://github.com/OpenLiberty/open-liberty/issues/6087)

Yes, I had a look into it, to understand better the use case. Do you think you still require something like this? As explained above, allowing injection of `Optional<JsonWebToken>` has a few limitations and I don't think we should allow it.

**Comment by hrstoyanov** [comment] 2020-03-30 16:08
If it is possible to dynamically check for the presence of token, or OpenLiberty got rid of that irritating error log,  I have no problem you guys closing this issue.

**Comment by radcortez** [comment] 2020-03-30 16:25
@hrstoyanov In Liberty, when you inject a token that is not present, what is the value that you get? Null? or just an exception?

**Comment by Emily-Jiang** [comment] 2020-03-30 22:16
@radcortez I remember there was a choice between making JsonWebToken as Dependent or RequestScoped. Obviously 'RequestScoped` was picked. I think with this issue, we should revisit this area and I think it simplies the solution a great deal if we update the JsonWebToken impl to be a Dependent bean. This release is the perfect one to do so.

**Comment by radcortez** [comment] 2020-03-30 22:46
Please, check the previous discussion about it here:
https://github.com/eclipse/microprofile-jwt-auth/issues/27

My concern about changing `JsonWebToken` from `RequestScoped` to `Dependent` is that it is potentially a huge backwards incompatible change. My guess is that a lot of developers inject `JsonWebToken` in `ApplicationScopedBeans` and we would just be breaking all of their apps with this change.

**Comment by sberyozkin** [comment] 2020-03-30 22:47
@Emily-Jiang Changing the scopes is too late for 1.2 and IMHO it is not worth going for such a significant change just to address this issue anyway while a simple solution such as injecting `JsonWebToken` returning null for all of its getters works. The amount of work across all containers would be pretty massive and I'd rather avoid doing it unless there were a very convincing reason for it. @RequestScoped works OK generally so lets keep it this way for now at least.

**Comment by sberyozkin** [comment] 2020-03-30 22:52
@rdebusscher The use case there is to support the situation where the user code itself wants to manage what to do. I'm pretty sure I recall one of the TCK tests hitting the endpoint without a token, this is how I actually noticed raw `null` can not be returned :-). 
I think this needs to be clarified

**Comment by rdebusscher** [comment] 2020-03-31 08:49
>We already have JsonWebToken.getRawToken() method which returns String which is supposed to represent whatever was in Authorization Bearer ..., IMHO there is no need for more methods if we are happy with the empty JWT object idea.

This is what we do already. so


    @Inject
    private JsonWebToken jwt;

succeeds and jwt.getRawToken() return null when there is no token in the header.

So if we clarify this behaviour in the spec (If there is no JWT, an EmptyToken is injected with all values to null), we are good to go.

**Comment by radcortez** [comment] 2020-03-31 09:04
@rdebusscher yes, this was the proposal. If we have a consensus here, I'll push a PR for this.

**Comment by sberyozkin** [comment] 2020-03-31 12:40
@radcortez Please do, as we have one more independent agreement :-)
CC @chunlongibm, @dblevins, Emily, others, FYI, hope it will work for everyone

**Comment by chunlongliang-ibm** [comment] 2020-03-31 19:04
we are good with latest proposal from @rdebusscher .  If there is no JWT in request, the bean will still be injected, and but the bean return the claims as null.

**Comment by radcortez** [comment] 2020-04-01 11:22
Made a proposal for spec update and added TCK: #178

**Closed** 2020-04-06 21:59 UTC
Labels: Specification Clarification, enhancement
