### ISSUE TITLE
Changing Java EE to Jakarta EE

### ISSUE THREAD

**Issue by keilw** [eclipse/microprofile-jwt-auth#233] opened 2020-12-28 01:38 UTC
As JWT-Auth 1.2 already uses Jakarta EE 8 these changes better should have been done before 1.2 went final.
The spec mentions Java EE in at least 13 places and old pre Jakarta EE JSRs like 375 as a depencency beside others especially half a dozen references to JSR 250.

All of these should be changed to the appropriate Jakarta EE successors.

**Comment by sberyozkin** [comment] 2021-01-06 21:19
@keilw yeah, a few references to the old JSR-250 in the `interoperability.adoc` (we should rename this doc I guess). I think the reason no one really touched that outdated text is that our EE TCK suite is basically non-existent or barely exists - that was certainly not a focus for `1.2` - like I said - the main goal was to make it live again and bring some practically useful base level non-breaking enhancements.
IMHO - this issue would actually fit the `MPJWT-2.0` scope. It its a large chunk of work - not only the editorial changes would have to be made but I think the EE TCK suite would have to be realized enforcing those spec updates. Jakarta EE experts like yourself, Darran, and other MP JWT colleagues can help for sure.
Cheers !

**Comment by sberyozkin** [comment] 2021-07-15 14:51
Closing as a duplicate of #246

**Closed** 2021-07-22 10:12 UTC
Labels: duplicate
